<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DUC-WkJ45fRW1MP" name="org.example.testRunner.runners" tests="18" failures="1" timestamp="2022-07-20T23:57:59 EET" time="273.225" errors="1">
  <testcase name="runScenario" time="12.183" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="9.743" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="18.089" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="16.609" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="18.826" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="20.479" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="12.231" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="19.150" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="17.053" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="17.629" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="11.050" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="17.550" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="11.232" classname="org.example.testRunner.runners">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:659)
at java.util.ArrayList.get(ArrayList.java:435)
at org.example.stepDefs.D07_followUsStepDef.openUrl(D07_followUsStepDef.java:26)
at ✽.https://demo.nopcommerce.com/new-online-store-is-open is opened in new tab(file:///C:/Users/mshukri/Downloads/Testing/Scholarship-FWD/Web%20frontend%20UI%20testing/demonopcommerce/src/main/resources/features/F07_followUs.feature:6)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="15.872" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="9.370" classname="org.example.testRunner.runners">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at org.example.stepDefs.D06_homeSlidersStepDef.clickSlider_1(D06_homeSlidersStepDef.java:21)
at ✽.user click on first slider and navigates to nokia verify url(file:///C:/Users/mshukri/Downloads/Testing/Scholarship-FWD/Web%20frontend%20UI%20testing/demonopcommerce/src/main/resources/features/F06_homeSliders.feature:4)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="11.978" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="19.358" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="14.823" classname="org.example.testRunner.runners"/>
  <system-out/>
</testsuite> <!-- org.example.testRunner.runners -->
